# Generated by Django 6.0.6 on 2026-06-25 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_dilevery_order_delivery'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.order'),
        ),
    ]
