# Generated by Django 6.0.6 on 2026-06-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_discription_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dilevery',
            new_name='delivery',
        ),
    ]
